import type { ValidationPreset, OverlayPreset } from './types';

export const validationPresets: ValidationPreset[] = [
  {
    id: 'innovid',
    name: 'Innovid',
    description: 'Innovid video ad delivery specifications',
    containerFormats: ['mp4', 'mov'],
    videoCodecs: ['h264', 'prores'],
    minDimensions: { width: 1920, height: 1080 },
    maxDimensions: { width: 1920, height: 1080 },
    frameRates: [23.976, 25, 29.97],
    requireProgressive: true,
    chromaSubsampling: '4:2:0',
    bitDepth: 8,
    audioCodec: 'aac',
    audioSampleRate: 48000,
    audioChannels: 2,
    minBitrate: 15000000,
    requireFastStart: false,
    loudnessTarget: -24,
    loudnessTolerance: 2,
    truePeakMax: -6,
  },
  {
    id: 'social-media-standard',
    name: 'Social Media - Standard',
    description: 'Standard settings for social media videos (Instagram, Facebook, Twitter, TikTok)',
    containerFormats: ['mp4', 'mov', 'm4v'],
    videoCodecs: ['h264', 'hevc', 'h265'],
    minDimensions: { width: 640, height: 480 },
    maxDimensions: { width: 3840, height: 2160 },
    frameRates: [23.976, 24, 25, 29.97, 30, 50, 59.94, 60],
    requireProgressive: true,
    chromaSubsampling: '4:2:0',
    bitDepth: 8,
    audioCodec: 'aac',
    audioSampleRate: 48000,
    audioChannels: 2,
    minBitrate: 1000000,
    maxBitrate: 50000000,
    requireFastStart: true,
    loudnessTarget: -14,
    loudnessTolerance: 1,
    truePeakMax: -1,
  },
  {
    id: 'broadcast-hd',
    name: 'Broadcast - HD 1080p',
    description: 'Professional broadcast settings for HD 1080p',
    containerFormats: ['mov', 'mxf', 'mp4'],
    videoCodecs: ['prores', 'h264', 'avc1'],
    minDimensions: { width: 1920, height: 1080 },
    maxDimensions: { width: 1920, height: 1080 },
    frameRates: [24, 25, 30, 50, 59.94, 60],
    requireProgressive: true,
    chromaSubsampling: '4:2:2',
    bitDepth: 10,
    audioCodec: 'pcm_s16le',
    audioSampleRate: 48000,
    audioChannels: 2,
    minBitrate: 10000000,
    maxBitrate: 50000000,
    requireFastStart: false,
    loudnessTarget: -23,
    loudnessTolerance: 0.5,
    truePeakMax: -2,
  },
  {
    id: 'broadcast-4k',
    name: 'Broadcast - 4K UHD',
    description: 'Broadcast settings for 4K Ultra HD',
    containerFormats: ['mov', 'mxf', 'mp4'],
    videoCodecs: ['prores', 'h265', 'hevc'],
    minDimensions: { width: 3840, height: 2160 },
    maxDimensions: { width: 3840, height: 2160 },
    frameRates: [24, 25, 30, 50, 60],
    requireProgressive: true,
    chromaSubsampling: '4:2:2',
    bitDepth: 10,
    audioCodec: 'pcm_s24le',
    audioSampleRate: 48000,
    audioChannels: 6,
    minBitrate: 50000000,
    maxBitrate: 200000000,
    requireFastStart: false,
    loudnessTarget: -23,
    loudnessTolerance: 0.5,
    truePeakMax: -2,
  },
  {
    id: 'youtube-vimeo',
    name: 'YouTube / Vimeo - Optimized',
    description: 'Optimized settings for streaming platforms like YouTube and Vimeo',
    containerFormats: ['mp4', 'mov'],
    videoCodecs: ['h264', 'hevc', 'h265'],
    minDimensions: { width: 1280, height: 720 },
    maxDimensions: { width: 3840, height: 2160 },
    frameRates: [24, 25, 30, 48, 50, 60],
    requireProgressive: true,
    chromaSubsampling: '4:2:0',
    bitDepth: 8,
    audioCodec: 'aac',
    audioSampleRate: 48000,
    audioChannels: 2,
    minBitrate: 8000000,
    maxBitrate: 68000000,
    requireFastStart: true,
    loudnessTarget: -14,
    loudnessTolerance: 1,
    truePeakMax: -1,
  },
  {
    id: 'stories-reels',
    name: 'Stories / Reels / Shorts',
    description: 'Settings for short vertical videos (9:16)',
    containerFormats: ['mp4', 'mov'],
    videoCodecs: ['h264', 'hevc'],
    minDimensions: { width: 1080, height: 1920 },
    maxDimensions: { width: 1080, height: 1920 },
    frameRates: [24, 25, 30, 60],
    requireProgressive: true,
    chromaSubsampling: '4:2:0',
    bitDepth: 8,
    audioCodec: 'aac',
    audioSampleRate: 48000,
    audioChannels: 2,
    minBitrate: 2000000,
    maxBitrate: 8000000,
    requireFastStart: true,
    loudnessTarget: -14,
    loudnessTolerance: 1,
    truePeakMax: -1,
  },
  {
    id: 'cinema-dci',
    name: 'Digital Cinema - DCI',
    description: 'Digital cinema settings compliant with DCI standard',
    containerFormats: ['mxf', 'mov'],
    videoCodecs: ['jpeg2000', 'prores'],
    minDimensions: { width: 2048, height: 1080 },
    maxDimensions: { width: 4096, height: 2160 },
    frameRates: [24, 25, 30, 48, 50, 60],
    requireProgressive: true,
    chromaSubsampling: '4:4:4',
    bitDepth: 12,
    audioCodec: 'pcm_s24le',
    audioSampleRate: 48000,
    audioChannels: 8,
    requireFastStart: false,
    loudnessTarget: -23,
    loudnessTolerance: 0.5,
    truePeakMax: -2,
  },
];

export const overlayPresets: OverlayPreset[] = [
    {
      id: 'story-9-16',
      name: 'Story (9:16)',
      aspectRatio: '9:16',
      ratioValue: 9/16,
      safeTitleMargin: 0.9,
      safeActionMargin: 0.8,
      description: 'Instagram Stories, TikTok, Reels',
      group: 'guides',
    },
    {
      id: 'vertical-4-5',
      name: 'Vertical (4:5)',
      aspectRatio: '4:5',
      ratioValue: 4/5,
      safeTitleMargin: 0.9,
      safeActionMargin: 0.8,
      description: 'Instagram Feed portrait',
      group: 'guides',
    },
    {
      id: 'square-1-1',
      name: 'Square (1:1)',
      aspectRatio: '1:1',
      ratioValue: 1,
      safeTitleMargin: 0.9,
      safeActionMargin: 0.8,
      description: 'Instagram, Facebook square posts',
      group: 'guides',
    },
    {
      id: 'landscape-16-9',
      name: 'Landscape (16:9)',
      aspectRatio: '16:9',
      ratioValue: 16/9,
      safeTitleMargin: 0.9,
      safeActionMargin: 0.8,
      description: 'YouTube, Vimeo, standard video',
      group: 'guides',
    },
    {
      id: 'wide-21-9',
      name: 'Cinema (21:9)',
      aspectRatio: '21:9',
      ratioValue: 21/9,
      safeTitleMargin: 0.9,
      safeActionMargin: 0.8,
      description: 'Cinematic widescreen',
      group: 'guides',
    },
    {
      id: 'legacy-4-3',
      name: 'Legacy (4:3)',
      aspectRatio: '4:3',
      ratioValue: 4/3,
      safeTitleMargin: 0.9,
      safeActionMargin: 0.8,
      description: 'Classic TV format',
      group: 'guides',
    },
    {
      id: 'ig-reels-organic',
      name: 'Instagram Reels - Organic (9:16)',
      aspectRatio: '9:16',
      ratioValue: 9/16,
      description: 'Instagram Reels organic safe zone',
      group: 'safezones',
      imagePath: 'Organic safe zones Reels.png',
    },
    {
      id: 'ig-reels-paid',
      name: 'Instagram Reels - Paid (9:16)',
      aspectRatio: '9:16',
      ratioValue: 9/16,
      description: 'Instagram Reels paid safe zone',
      group: 'safezones',
      imagePath: 'Paid Safe zones Instagram Reels.png',
    },
    {
      id: 'pinterest-1-1',
      name: 'Pinterest (1:1)',
      aspectRatio: '1:1',
      ratioValue: 1,
      description: 'Pinterest square safe zone',
      group: 'safezones',
      imagePath: 'Pinterest 1x1 Safezone.png',
    },
    {
      id: 'tiktok-9-16',
      name: 'TikTok (9:16)',
      aspectRatio: '9:16',
      ratioValue: 9/16,
      description: 'TikTok video safe zone',
      group: 'safezones',
      imagePath: 'TikTok Videos Safe Zone.png',
    },
    {
      id: 'youtube-shorts-9-16',
      name: 'YouTube Shorts (9:16)',
      aspectRatio: '9:16',
      ratioValue: 9/16,
      description: 'YouTube Shorts safe zone',
      group: 'safezones',
      imagePath: 'Youtube Shorts Safe Zone.png',
    },
];

export const getValidationPreset = (id: string): ValidationPreset | undefined => {
  return validationPresets.find(p => p.id === id);
};

export const getOverlayPreset = (id: string): OverlayPreset | undefined => {
  return overlayPresets.find(p => p.id === id);
};